version: '2'

services:
    database:
        image: mongo:latest
        restart: always

    app:
        depends_on:
            - database
        image: joatmon08/stars:latest
        ports:
            - 5000:80
        environment:
            - DB_NAME=test
            - DB_URI=mongodb://database:27017/test
        restart: always
